### ISSUE TITLE
[Suggestion] Config option to replace vanilla blocks with Fragile Glass ones

### ISSUE THREAD

**Issue by DWX12** [fredtargaryen/Fragile-Glass#13]
Had an idea for the Fragile Glass mod to get more use and that would be to have a config option to replace all vanilla counterparts into Fragile Glass blocks. Possibly just a reversing or swapping of the mod where you'd use the cauldron to create "sturdy" (vanilla) glass, ice, and stone.

Could make it a challenge with Tough as Nails in an icy biome or if zombies (or other mobs) could break through glass instead of just doors. Maybe an interesting pack where most of the ground isn't safe to walk on.

Could be a real interesting idea and all it would take is just the swapping of some recipes and additions to the config.

**Comment by fredtargaryen** [comment]
Hi, thank you for the suggestions!

What I will definitely do is make sure there are config lines for making vanilla glass and ice fragile. Weak stone does its own weird thing so there's no proper way of making that happen with normal stone, but I will include the lines for glass and ice; thanks.

As for reversing the recipes: do people like this kind of thing? Surely it's just annoying when you're playing and a mod does the opposite of what it is supposed to do.

Also I have tried making the ground fragile and moving around and it is nowhere near as fun as it sounds!

Right now walking Zombies can't break through glass because they can't move fast enough - maybe a baby could - But you did remind me that I was supposed to make a similar system for entities and their break speeds, so that will become possible at some point.

**Comment by DWX12** [comment]
You have to remember that certain worlds and play modes like skyblock, skygrid, and adventure maps came about from people wanting to try different things out and keep Minecraft fresh and new.

I can imagine people using your mod in adventure maps like a crumbling tomb for example or even a map centered around volcanoes and unstable ground. Hell, when I was younger, I used to play "the floor is lava" like so many other kids.

The only other thing this mod could use is the "Kool Aid" man :P

**Comment by fredtargaryen** [comment]
Since last time there is now a config system for changing the speed needed for pretty much any server entity to set off fragile blocks.

What I'm thinking of doing, as something that is slightly easier for me and more flexible for everyone else, is to make a JSON-based recipe system for the sugar cauldron, and let people use CraftTweaker or a resource pack to swap recipes, or change them in other ways, if they want to. How does that sound?

Haha, I did think of the Kool-Aid man as a possible use case actually.

**Comment by Ravin890** [comment]
I just need to find a mod which adds him, then morph mod into him and you know the fun (had same idea when you added the extra block thing lol)

**Comment by fredtargaryen** [comment]
I'm going to go ahead and close this issue now. The new system solves the bulk of your suggestion: make fragile blocks behave like non-fragile ones, and vice versa. Going as far as switching names, recipes etc. is not worth the effort, I think - I don't know any other mods that do that and I still don't see how it adds any significant value to the game.

Thank you so much for your suggestion!
