### ISSUE TITLE
[Suggestion]Whitelist as Opposed to set items

### ISSUE THREAD

**Issue by Ravin890** [fredtargaryen/Fragile-Glass#5]
Would it be possible to allow for the mod to have a whitelist for blocks to break like the fragile glass in the mod as opposed to just it being the items added by the mod, that way you could modify the properties of any glass added by any mod, ect.?

**Comment by fredtargaryen** [comment]
Hi; sorry for taking so long to reply!

This is a really interesting question and would be ideal for the mod. I would like to have it this way but I don't think it is really possible. If it is, I think it will be a big undertaking which I don't really have time for right now.

My thinking is like this:

- The fragility code as it stands is based around Tile Entities, and only fragile blocks will have the TileEntityFragile.
- Assuming this is the best way to implement fragility:
-- Right at the time of writing, I think I've come up with a way to change an existing TileEntity to become fragile...
-- I don't know of any good way to force a block to have a Tile Entity.
- I don't know any better way to implement the current features of the mod in Minecraft.

The question's definitely captured my attention, and I will attempt to set up the whitelist for blocks that have Tile Entities, but no guarantees!

**Comment by fredtargaryen** [comment]
Update: I have made a way to change any TileEntity, mod or vanilla, to become fragile. This can be done in fragileglassft_blocklist.cfg, where the exact behaviour of the fragile block can be specified.

**Comment by fredtargaryen** [comment]
I now have a way to do this with any block, tile entity or not. Here is a beta version which works nicely for me; I'm gonna wait for (hopefully) some feedback/suggestions before making it a proper release.

https://minecraft.curseforge.com/projects/fragile-glass-and-thin-ice/files/2635272

If you have any feedback/suggestions for this I'd love to hear it!

**Comment by Ravin890** [comment]
So testing around numbers first, so your default value will break blocks when you jump or walk onto them from a slab (0.165) and seeing which value will break the from jumping but not walking off a slab.
Found the value to be around 0.3 but jumping and placing blocks is still allowed. If you stop jumping when you place the last block it will be fine but forgetting will break all the blocks. So I like your value. Though is there a method of getting faster while falling

**Comment by fredtargaryen** [comment]
First off, thanks for this; I don't get feedback very often and really appreciate this input.

0.165 (and this is pretty much a client side calculation as I can't get speed on the server) is roughly the speed of a sprinting player. If I put the value up to 0.3 that unfortunately stops people being able to break blocks by sprinting into them, which I think is necessary for aesthetics.

Getting faster while falling: the break code pretends your hitbox is further ahead than it actually is, to break glass slightly before you would actually collide with it. Therefore in theory if you fell through fragile glass forever (or you sped up your fall in some way), you would speed up the same as if there were no glass at all. The glass isn't supposed to affect your speed at all; if it is, that's a problem.

As for jumping and placing blocks, I think you only have yourself to blame if you're trying to use fragile blocks for climbing or scaffolding!!

Metadata is a very good question, though in the spirit of the new systems it would be better to use the blockstate names instead of metadata numbers. I have no idea where you would use this but I will definitely think about it.

Elytras: I believe players using any mode of transport should be able to break blocks if they're going fast enough. As long as the entity is going above the _entity's_ breaking speed _and_ the _block's_ breaking speed, however they are travelling, they should be able to break the block.

**Comment by Ravin890** [comment]
Well the glass poles was more of an easter egg than complaint either way XD

**Comment by fredtargaryen** [comment]
I haven't tested mod interaction yet but I get the feeling I put the config loading code in the wrong place so it won't play...

**Comment by Ravin890** [comment]
So testing some, and realized that just walking towards your windows will break the glass.
Also saw the door thing and thought of testing enderIO's fused quartz and looks like using [color=] works.

*test was with both a block added in and fragile glass, so windows will be an issue if you just walk to them... (might play with the speed to see if there is a better number)

**Comment by fredtargaryen** [comment]
About [color], basically any property should work as intended i.e. snowy, facing, open, powered etc., provided it doesn't break some other rule of Minecraft, e.g. the door thing which doesn't always work (I think because it's a multi-block thing).
As for windows breaking by just walking, that's terrible, but I don't see that on my end.
What does your config file look like - or at least the line you were testing?

**Comment by Ravin890** [comment]
Hm... could be a typo honestly I will check and see if that is it.

**Comment by fredtargaryen** [comment]
Well, I do have to look at how it works with other mods too. One of my biggest Floocraft bugs came from not doing that.
Squake is a great idea for a mod!
